#!/bin/sh

set -e

THAT_NAME=capsrvd

# app name : capsrvd
THAT_APP_NAME=$THAT_NAME

# user name: capsrvd (change if needed)
THAT_APP_USER=$THAT_NAME

THAT_APP_RUN=/usr/bin/$THAT_APP_NAME
# no home
THAT_APP_HOME=/var/run/$THAT_APP_NAME

THAT_APP_LOGDIR=/var/log/$THAT_APP_NAME
THAT_APP_CONFDIR=/etc/$THAT_APP_NAME

THAT_APP_LOGROTATEDIR=/etc/logrotate.d
THAT_APP_SYSTEMDDIR=/etc/systemd/system

# /etc/capsrvd/capsrvd.conf.json.example
THAT_APP_EXAPLE_CONF=$THAT_APP_CONFDIR/$THAT_APP_NAME.conf.json.example
# /etc/capsrvd/capsrvd.conf.json
THAT_APP_CONF=$THAT_APP_CONFDIR/$THAT_APP_NAME.conf.json

# /usr/lib/capsrvd/index.js
THAT_APP_INDEX_SCRIPT=/usr/lib/$THAT_APP_NAME/index.js

# /usr/share/capsrvd/capsrvd
THAT_APP_LOGROTATE_SCRIPT=/usr/share/$THAT_APP_NAME/$THAT_APP_NAME
# /usr/logrotate.d/capsrvd
THAT_APP_LOGROTATE=$THAT_APP_LOGROTATEDIR/$THAT_APP_NAME
# /usr/share/capsrvd/capsrvd
THAT_APP_SYSTEMD_SCRIPT=/usr/share/$THAT_APP_NAME/$THAT_APP_NAME.service
# /usr/logrotate.d/capsrvd
THAT_APP_SYSTEMD=$THAT_APP_SYSTEMDDIR/$THAT_APP_NAME.service

# test user exists
if id "$THAT_APP_USER" > /dev/null 2>&1; then
	echo "user $THAT_APP_USER exists"
else
	echo "add user: $THAT_APP_USER"

	useradd -rMU $THAT_APP_USER
fi

# setup execution on run script
[ ! -x $THAT_APP_RUN ] && \
	chmod +x $THAT_APP_RUN

# change log directory permissions
[ -d $THAT_APP_LOGDIR ] && \
	chown -R $THAT_APP_USER $THAT_APP_LOGDIR

# move /etc/capsrvd/capsrvd.conf.json.example to /etc/capsrvd/capsrvd.conf.json if its first installation
[ ! -f $THAT_APP_CONF ] && [ -f $THAT_APP_EXAPLE_CONF ] && \
	cp $THAT_APP_EXAPLE_CONF $THAT_APP_CONF

# setup config directory permissions
[ -d $THAT_APP_CONFDIR ] && \
	chmod 750 $THAT_APP_CONFDIR && \
	chown -R $THAT_APP_USER $THAT_APP_CONFDIR

# install logrotate script
if [ -d $THAT_APP_LOGROTATEDIR ]; then
	[ ! -f $THAT_APP_LOGROTATE ] && [ -f $THAT_APP_LOGROTATE_SCRIPT ] && \
		echo "instal logroate script: $THAT_APP_LOGROTATE" && \
		cp $THAT_APP_LOGROTATE_SCRIPT $THAT_APP_LOGROTATE
fi

# install systemd script
if [ -d $THAT_APP_SYSTEMDDIR ]; then
	[ -f $THAT_APP_SYSTEMD_SCRIPT ] && [ ! -f $THAT_APP_SYSTEMD ] && \
		cp $THAT_APP_SYSTEMD_SCRIPT $THAT_APP_SYSTEMD && \
		systemctl daemon-reload && \
		systemctl enable $THAT_APP_NAME && \
		systemctl restart $THAT_APP_NAME
fi

