#!/bin/sh

set -e

TARGET_NAME=capsrvd
# user name: capsrvd (change if needed)
TARGET_USER=$TARGET_NAME
TARGET_GID=172
TARGET_UID=172

TARGET_RUN=/usr/bin/$TARGET_NAME
TARGET_HOME=/usr/lib/$TARGET_NAME
TARGET_LOGDIR=/var/log/$TARGET_NAME

TARGET_CONFDIR=/etc/$TARGET_NAME
# /etc/capsrvd/capsrvd.conf.json
TARGET_CONF=$TARGET_CONFDIR/$TARGET_NAME.conf.json
# /etc/capsrvd/capsrvd.conf.json.example
TARGET_EXAMPLE_CONF=$TARGET_CONFDIR/$TARGET_NAME.conf.json.example

# /usr/lib/capsrvd/index.js
TARGET_INDEX=/usr/lib/$TARGET_NAME/index.js

#
TARGET_DATADIR=/usr/share/$TARGET_NAME

# logrotate section
LOGROTATEDIR=/etc/logrotate.d
LOGROTATE=$LOGROTATEDIR/$TARGET_NAME
LOGROTATE_SCRIPT=$TARGET_DATADIR/logrotate

# systemd section
SYSTEMDDIR=/etc/systemd/system
SYSTEMD=$SYSTEMDDIR/$TARGET_NAME.service
SYSTEMD_SCRIPT=$TARGET_DATADIR/systemd

# monit section
MONITDIR=/etc/monit/conf.d
MONIT=$MONITDIR/$TARGET_NAME.conf
MONIT_SCRIPT=$TARGET_DATADIR/monit
SYSTEMD_MONIT_SCRIPT=$TARGET_DATADIR/monit.systemd

# postinst
if [ "$1" = purge ]; then

# remove log dir
[ -d $THAT_APP_LOGDIR ] &&
    rm -rf $TARGET_LOGDIR

# remove main config
[ -d $TARGET_CONFDIR ] && \
    rm -rf $TARGET_CONFDIR

# remove logrotate config
[ -f $LOGROTATE ] && \
    rm $LOGROTATE

# remove systemd
[ -f $SYSTEMD ] && \
    rm $SYSTEMD

# remove monit
[ -f $MONIT ] && \
    rm $MONIT

# test user exists
if id "$TARGET_USER" > /dev/null 2>&1; then
    echo "remove user: $TARGET_USER"
    userdel $TARGET_USER
#    groupdel $TARGET_USER
fi

fi

exit 0
