#!/bin/sh

set -e

TARGET_NAME=capsrvd
# user name: capsrvd (change if needed)
TARGET_USER=$TARGET_NAME
TARGET_GID=172
TARGET_UID=172

TARGET_RUN=/usr/bin/$TARGET_NAME
TARGET_HOME=/usr/lib/$TARGET_NAME
TARGET_LOGDIR=/var/log/$TARGET_NAME

TARGET_CONFDIR=/etc/$TARGET_NAME
# /etc/capsrvd/capsrvd.conf.json
TARGET_CONF=$TARGET_CONFDIR/$TARGET_NAME.conf.json
# /etc/capsrvd/capsrvd.conf.json.example
TARGET_EXAMPLE_CONF=$TARGET_CONFDIR/$TARGET_NAME.conf.json.example

# /usr/lib/capsrvd/index.js
TARGET_INDEX=/usr/lib/$TARGET_NAME/index.js

#
TARGET_DATADIR=/usr/share/$TARGET_NAME

# logrotate section
LOGROTATEDIR=/etc/logrotate.d
LOGROTATE=$THAT_APP_LOGROTATEDIR/$TARGET_NAME
LOGROTATE_SCRIPT=$TARGET_DATADIR/logrotate

# systemd section
SYSTEMDDIR=/etc/systemd/system
SYSTEMD=$SYSTEMDDIR/$TARGET_NAME.service
SYSTEMD_SCRIPT=$TARGET_DATADIR/systemd
SYSTEMD_RUNDIR=/run/systemd/system

# monit section
MONITDIR=/etc/monit/conf.d
MONIT=$MONITDIR/$TARGET_NAME.conf
MONIT_SCRIPT=$TARGET_DATADIR/monit

# postinst
if [ "$1" = configure ]; then

# test user exists
if id "$TARGET_USER" > /dev/null 2>&1; then
    echo "user $TARGET_USER exists"
else
    echo "add group: $TARGET_USER gid: $TARGET_GID"
    groupadd --system --gid $TARGET_GID $TARGET_NAME
    useradd --system --no-create-home --gid $TARGET_GID --uid $TARGET_UID --disabled-password $TARGET_NAME
fi

# setup execution on run script
[ ! -x $TARGET_RUN ] && \
    chmod +x $TARGET_RUN

# change log directory permissions
[ -d $TARGET_LOGDIR ] && \
    chown -R $TARGET_USER $TARGET_LOGDIR

# move /etc/capsrvd/capsrvd.conf.json.example to /etc/capsrvd/capsrvd.conf.json if its first installation
[ ! -f $TARGET_CONF ] && [ -f $TARGET_EXAMPLE_CONF ] && \
    mv $TARGET_EXAMPLE_CONF $TARGET_CONF

# setup config directory permissions
[ -d $TARGET_CONFDIR ] && \
    chmod 750 $TARGET_CONFDIR && \
    chown -R $TARGET_USER $TARGET_CONFDIR

# install logrotate script
if [ -d $LOGROTATEDIR ]; then
    [ ! -f $LOGROTATE ] && [ -f $LOGROTATE_SCRIPT ] && \
	echo "instal logroate script: $LOGROTATE" && \
	cp $LOGROTATE_SCRIPT $LOGROTATE
fi

if [ -d $MONITDIR ]; then
    [ ! -f $MONIT ] && [ -f $MONIT_SCRIPT ] && \
	echo "instal monit script: $MONIT_SCRIPT" && \
	cp $MONIT_SCRIPT $MONIT
else
     if [ -d $SYSTEMD_RUNDIR ]; then
	[ -d $SYSTEMDDIR ] && [ ! -f $SYSTEMD ] && [ -f $SYSTEMD_SCRIPT ] && \
	    echo "install systemd script: $SYSTEMD" && \
	    cp $SYSTEMD_SCRIPT $SYSTEMD
    fi
fi

fi # configure

exit 0
