#!/bin/sh

set -e

THAT_NAME=capsrvd

# app name : capsrvd
THAT_APP_NAME=$THAT_NAME

# user name: capsrvd (change if needed)
THAT_APP_USER=$THAT_NAME

THAT_APP_RUN=/usr/bin/$THAT_APP_NAME
# no home
THAT_APP_HOME=/var/run/$THAT_APP_NAME

THAT_APP_LOGDIR=/var/log/$THAT_APP_NAME
THAT_APP_CONFDIR=/etc/$THAT_APP_NAME

THAT_APP_LOGROTATEDIR=/etc/logrotate.d

# /etc/capsrvd/capsrvd.conf.json.example
THAT_APP_EXAPLE_CONF=$THAT_APP_CONFDIR/$THAT_APP_NAME.conf.json.example

# /etc/capsrvd/capsrvd.conf.json
THAT_APP_CONF=$THAT_APP_CONFDIR/$THAT_APP_NAME.conf.json

# /usr/lib/capsrvd/index.js
THAT_APP_INDEX_SCRIPT=/usr/lib/$THAT_APP_NAME/index.js

# /usr/share/capsrvd/capsrvd
THAT_APP_LOGROTATE_SCRIPT=/usr/share/$THAT_APP_NAME/$THAT_APP_NAME

# /usr/logrotate.d/capsrvd
THAT_APP_LOGROTATE=$THAT_APP_LOGROTATEDIR/$THAT_APP_NAME

if [ "$1" = configure ]; then

	# test user exists
	if id "$THAT_APP_USER" > /dev/null 2>&1; then
		echo "user $THAT_APP_USER exists"
	else
		echo "add user: $THAT_APP_USER"

		adduser --system \
			--quiet \
			--home "$THAT_APP_HOME" \
			--no-create-home \
			--disabled-password \
			--group "$THAT_APP_USER"
	fi

	# setup execution on run script
	[ ! -x $THAT_APP_RUN ] && \
		chmod +x $THAT_APP_RUN

	# change log directory permissions
	[ -d $THAT_APP_LOGDIR ] && \
		chown -R $THAT_APP_USER $THAT_APP_LOGDIR

	# move /etc/capsrvd/capsrvd.conf.json.example to /etc/capsrvd/capsrvd.conf.json if its first installation
	[ ! -f $THAT_APP_CONF ] && [ -f $THAT_APP_EXAPLE_CONF ] && \
		mv $THAT_APP_EXAPLE_CONF $THAT_APP_CONF

	# setup config directory permissions
	[ -d $THAT_APP_CONFDIR ] && \
		chmod 750 $THAT_APP_CONFDIR && \
		chown -R $THAT_APP_USER $THAT_APP_CONFDIR

	# install logrotate script
	if [ -d $THAT_APP_LOGROTATEDIR ]; then
		[ ! -f $THAT_APP_LOGROTATE ] && [ -f $THAT_APP_LOGROTATE_SCRIPT ] && \
			echo "instal logroate script: $THAT_APP_LOGROTATE" && \
			cp $THAT_APP_LOGROTATE_SCRIPT $THAT_APP_LOGROTATE
	fi

	# update systemd configuration
	systemctl daemon-reload

	# enable startup
	systemctl enable $THAT_APP_NAME

	systemctl start $THAT_APP_NAME
fi